# Generated by Django 3.0 on 2020-02-27 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1023)),
                ('body', models.CharField(max_length=16383)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reply_body', models.CharField(max_length=16383, null=True)),
                ('reply_at', models.DateTimeField(null=True)),
                ('issue_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_issue_user', to=settings.AUTH_USER_MODEL)),
                ('reply_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
