# Generated by Django 3.0.3 on 2020-02-28 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reply_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply_user',
        ),
        migrations.AlterField(
            model_name='message',
            name='issue_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_body', models.CharField(max_length=16383)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reply_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Reply'),
        ),
    ]
